# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='photos/')),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('inCart', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
